### ISSUE TITLE
how to download the weights, code not contain?

### ISSUE THREAD

**Issue by mlinxiang** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#1]
The weights folder contains three weights files. The comparison.h5 is for first five classes and performance.h5 is for first eight classes. solo.h5 is for hand detection.  but no link

**Comment by MahmudulAlam** [comment]
Hi @mlinxiang 
Just click on the [download|weights] badge which will redirect you to MEGA. 
OR, 
Go to this link: https://mega.nz/#F!y9dBAKiK!gDd8AZCax2IIUGo4W4ixUw

**Comment by mlinxiang** [comment]
the link can't visit 
![image](https://user-images.githubusercontent.com/6283983/66478277-96752b80-eacc-11e9-9b62-eff07de3b530.png)

**Comment by MahmudulAlam** [comment]
MEGA may be blocked in your country. Use a VPN to access the link.

**Comment by lgcy** [comment]
> MEGA may be blocked in your country. Use a VPN to access the link.

i use the vpn, but i can't visit, could you provide the Google cloud disk link?

**Comment by MahmudulAlam** [comment]
Hi @lgcy
Can you access the following dropbox link and download the weight files? Please, let me know.
https://www.dropbox.com/s/bqrzxcrt2x0mitr/weights.zip?dl=0

**Comment by lgcy** [comment]
@MahmudulAlam  Thanks , i can  access the dropbox link and download the weight files
