### ISSUE TITLE
What python version does this use?

### ISSUE THREAD

**Issue by M-Davies** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#10]

**Comment by MahmudulAlam** [comment]
@M-Davies 
python 3.8

**Comment by M-Davies** [comment]
Any specific minor version?

**Comment by MahmudulAlam** [comment]
@M-Davies 
Hi, It should work without any problem in any python 3 versions. If you are facing any specific issues let me know.

**Comment by M-Davies** [comment]
No issues related to this project but I was a little confused on what one to use considering the lack of documentation. Thanks for clarifying
