### ISSUE TITLE
Difference of classes5.h5 and classes8.h5

### ISSUE THREAD

**Issue by danieltanimanuel** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#13]
Hi, May i know the difference when training classes5 and classes8? are the difference from the dataset used for training by excluding SingleSix, SingleSeven, SingleEight or there are other modification such as changing the model structure or parameters?

Thanks

**Comment by MahmudulAlam** [comment]
Hello @danieltanimanuel 

classes5 model is trained on the first 5 classes only, excluding SingleSix, SingleSeven, SingleEight. all the parameters are same.
