### ISSUE TITLE
left hand? 

### ISSUE THREAD

**Issue by myhjiang** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#17]
Hi, first it's really cool work!

Is the left hand included in the training images? I have been playing around with some of my own images and it seems that it doesn't really recognize the left hand in a palm-down position... 

If I want to include the left hand, do you think it would be possible if I train the network with the image flipped?

**Comment by MahmudulAlam** [comment]
@myhjiang 
Hello, training images only include right-hand images. You can horizontally flip those images to generate left-hand images and train the network.
