### ISSUE TITLE
Problem of weights

### ISSUE THREAD

**Issue by VIPL-chongmou** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#2]
Hi,when load the solo.h5(In solo.py line 14:"self.model.load_weights(weights)") it will report errors:
Process finished with exit code -1073741819 (0xC0000005)
keras2.2.5+tensorflow1.14.0+cuda10.0

**Comment by MahmudulAlam** [comment]
Hello. 
Try with TensorFlow==1.11.0
and let me know it works or not.
