### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'weights/performance.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by Jasonmes** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#3]
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'weights/performance.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by Jasonmes** [comment]
where is performance.h5

**Comment by MahmudulAlam** [comment]
Hi @Jasonmes 
Thanks for your interest. 
You have to download the weights files separately as their size exceeds the GitHub file size limit. You can download the files by clicking on this option in the Readme section. 

[![Downloads](https://img.shields.io/badge/download-weights-green.svg?style=popout-flat&logo=mega)](https://mega.nz/#F!y9dBAKiK!gDd8AZCax2IIUGo4W4ixUw)

Also, you can access the files using the following link: 
https://mega.nz/#F!y9dBAKiK!gDd8AZCax2IIUGo4W4ixUw

If you have problem to access this link then you can download the weights files from the following dropbox link: 
https://www.dropbox.com/s/bqrzxcrt2x0mitr/weights.zip?dl=0
Hope this helps.
