### ISSUE TITLE
can use mobilenet and run on mobile devices?

### ISSUE THREAD

**Issue by mlinxiang** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#4]

**Comment by MahmudulAlam** [comment]
Hi @mlinxiang 
Using mobilenet in the network will be straight forward. In the [model() function](https://github.com/MahmudulAlam/Unified-Gesture-and-Fingertip-Detection/blob/e0e8986fb6da8811a72af02f1ea2cd1fb613802b/net/network.py#L6) change the VGG16 with mobilenet. 

from keras.applications import MobileNetV2
model = MobileNetV2(include_top=False, input_shape=(128, 128, 3))

Then just train the model.
