### ISSUE TITLE
cannot download the pretrained weights

### ISSUE THREAD

**Issue by cwlinghk** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#6]
The download process always stops in the mid way. Is there any other download sources? Thank you very much.

**Comment by MahmudulAlam** [comment]
Hi @cwlinghk 
I have provided two download links: [MEGA](https://mega.nz/#F!6stCxY5b!oB-3279KkhfhRULQFQO7yQ) and [OneDrive](https://www.dropbox.com/sh/7pbfrgaor678eft/AAA8r5ADlMde0WkAtJQO_lo5a?dl=0). Try both of them and let me know if none of them are working.

**Comment by Hanswanglin** [comment]
@cwlinghk I think what you say about the pretrained weights is the **vgg16_weights**, Is that ?
